import { db } from '@/db';
import { genreCriteria } from '@/db/schema';

async function main() {
    const sampleCriteria = [
        // AI Writing - 4 metrics
        {
            category: 'AI Writing',
            metricKey: 'contentQuality',
            metricLabel: 'Content Quality',
            metricIcon: '✨',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            category: 'AI Writing',
            metricKey: 'speedEfficiency',
            metricLabel: 'Speed & Efficiency',
            metricIcon: '⚡',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            category: 'AI Writing',
            metricKey: 'languageSupport',
            metricLabel: 'Language Support',
            metricIcon: '🌐',
            metricColor: '#3b82f6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            category: 'AI Writing',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        // AI Tools - 4 metrics
        {
            category: 'AI Tools',
            metricKey: 'usabilityDesign',
            metricLabel: 'Usability & Design',
            metricIcon: '🎨',
            metricColor: '#ec4899',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            category: 'AI Tools',
            metricKey: 'integrationsAPI',
            metricLabel: 'Integrations & API',
            metricIcon: '🔌',
            metricColor: '#6366f1',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            category: 'AI Tools',
            metricKey: 'communityDocs',
            metricLabel: 'Community & Docs',
            metricIcon: '📚',
            metricColor: '#14b8a6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            category: 'AI Tools',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        // Design - 4 metrics
        {
            category: 'Design',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            category: 'Design',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '⭐',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            category: 'Design',
            metricKey: 'templates',
            metricLabel: 'Templates',
            metricIcon: '📐',
            metricColor: '#ec4899',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            category: 'Design',
            metricKey: 'collaboration',
            metricLabel: 'Collaboration',
            metricIcon: '👥',
            metricColor: '#3b82f6',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        // Video Editing - 4 metrics
        {
            category: 'Video Editing',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            category: 'Video Editing',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '🎬',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            category: 'Video Editing',
            metricKey: 'renderingSpeed',
            metricLabel: 'Rendering Speed',
            metricIcon: '⚡',
            metricColor: '#06b6d4',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            category: 'Video Editing',
            metricKey: 'exportOptions',
            metricLabel: 'Export Options',
            metricIcon: '📤',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        // Productivity - 4 metrics
        {
            category: 'Productivity',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            category: 'Productivity',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            category: 'Productivity',
            metricKey: 'automation',
            metricLabel: 'Automation',
            metricIcon: '🤖',
            metricColor: '#14b8a6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            category: 'Productivity',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        // Development - 4 metrics
        {
            category: 'Development',
            metricKey: 'codeQuality',
            metricLabel: 'Code Quality',
            metricIcon: '💻',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            category: 'Development',
            metricKey: 'performance',
            metricLabel: 'Performance',
            metricIcon: '🚀',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            category: 'Development',
            metricKey: 'debugging',
            metricLabel: 'Debugging',
            metricIcon: '🐛',
            metricColor: '#ef4444',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            category: 'Development',
            metricKey: 'documentation',
            metricLabel: 'Documentation',
            metricIcon: '📖',
            metricColor: '#3b82f6',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        // Marketing - 4 metrics
        {
            category: 'Marketing',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            category: 'Marketing',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '🎯',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            category: 'Marketing',
            metricKey: 'analytics',
            metricLabel: 'Analytics',
            metricIcon: '📊',
            metricColor: '#06b6d4',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            category: 'Marketing',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        // E-commerce - 4 metrics
        {
            category: 'E-commerce',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            category: 'E-commerce',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '🛒',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            category: 'E-commerce',
            metricKey: 'paymentOptions',
            metricLabel: 'Payment Options',
            metricIcon: '💳',
            metricColor: '#10b981',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            category: 'E-commerce',
            metricKey: 'scalability',
            metricLabel: 'Scalability',
            metricIcon: '📈',
            metricColor: '#3b82f6',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        // AI Image Generation - 4 metrics
        {
            category: 'AI Image Generation',
            metricKey: 'imageQuality',
            metricLabel: 'Image Quality',
            metricIcon: '🎨',
            metricColor: '#ec4899',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            category: 'AI Image Generation',
            metricKey: 'speedEfficiency',
            metricLabel: 'Speed & Efficiency',
            metricIcon: '⚡',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            category: 'AI Image Generation',
            metricKey: 'styleOptions',
            metricLabel: 'Style Options',
            metricIcon: '🖼️',
            metricColor: '#8b5cf6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            category: 'AI Image Generation',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        // AI Coding - 4 metrics
        {
            category: 'AI Coding',
            metricKey: 'codeQuality',
            metricLabel: 'Code Quality',
            metricIcon: '💻',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            category: 'AI Coding',
            metricKey: 'speedEfficiency',
            metricLabel: 'Speed & Efficiency',
            metricIcon: '⚡',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            category: 'AI Coding',
            metricKey: 'languageSupport',
            metricLabel: 'Language Support',
            metricIcon: '🌐',
            metricColor: '#3b82f6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            category: 'AI Coding',
            metricKey: 'integrationOptions',
            metricLabel: 'Integration Options',
            metricIcon: '🔌',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        // AI Assistant - 4 metrics
        {
            category: 'AI Assistant',
            metricKey: 'conversationQuality',
            metricLabel: 'Conversation Quality',
            metricIcon: '💬',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            category: 'AI Assistant',
            metricKey: 'knowledgeAccuracy',
            metricLabel: 'Knowledge Accuracy',
            metricIcon: '🎯',
            metricColor: '#10b981',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            category: 'AI Assistant',
            metricKey: 'integrationOptions',
            metricLabel: 'Integration Options',
            metricIcon: '🔌',
            metricColor: '#6366f1',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            category: 'AI Assistant',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#f59e0b',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        // Email Marketing - 4 metrics
        {
            category: 'Email Marketing',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            category: 'Email Marketing',
            metricKey: 'automation',
            metricLabel: 'Automation',
            metricIcon: '🤖',
            metricColor: '#14b8a6',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            category: 'Email Marketing',
            metricKey: 'analytics',
            metricLabel: 'Analytics',
            metricIcon: '📊',
            metricColor: '#06b6d4',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            category: 'Email Marketing',
            metricKey: 'deliverability',
            metricLabel: 'Deliverability',
            metricIcon: '📨',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        // SEO Tools - 4 metrics
        {
            category: 'SEO Tools',
            metricKey: 'accuracy',
            metricLabel: 'Accuracy',
            metricIcon: '🎯',
            metricColor: '#10b981',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            category: 'SEO Tools',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '🔍',
            metricColor: '#8b5cf6',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            category: 'SEO Tools',
            metricKey: 'reporting',
            metricLabel: 'Reporting',
            metricIcon: '📈',
            metricColor: '#3b82f6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            category: 'SEO Tools',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#f59e0b',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        // Social Media - 4 metrics
        {
            category: 'Social Media',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            category: 'Social Media',
            metricKey: 'scheduling',
            metricLabel: 'Scheduling',
            metricIcon: '📅',
            metricColor: '#ec4899',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            category: 'Social Media',
            metricKey: 'analytics',
            metricLabel: 'Analytics',
            metricIcon: '📊',
            metricColor: '#06b6d4',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            category: 'Social Media',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        // Project Management - 4 metrics
        {
            category: 'Project Management',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            category: 'Project Management',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '✅',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            category: 'Project Management',
            metricKey: 'collaboration',
            metricLabel: 'Collaboration',
            metricIcon: '👥',
            metricColor: '#3b82f6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            category: 'Project Management',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        // CRM - 4 metrics
        {
            category: 'CRM',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            category: 'CRM',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '📋',
            metricColor: '#f59e0b',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            category: 'CRM',
            metricKey: 'automation',
            metricLabel: 'Automation',
            metricIcon: '🤖',
            metricColor: '#14b8a6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            category: 'CRM',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        // Analytics - 4 metrics
        {
            category: 'Analytics',
            metricKey: 'accuracy',
            metricLabel: 'Accuracy',
            metricIcon: '🎯',
            metricColor: '#10b981',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            category: 'Analytics',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '📊',
            metricColor: '#06b6d4',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            category: 'Analytics',
            metricKey: 'visualization',
            metricLabel: 'Visualization',
            metricIcon: '📈',
            metricColor: '#8b5cf6',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            category: 'Analytics',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#f59e0b',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        // Automation - 4 metrics
        {
            category: 'Automation',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            category: 'Automation',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            category: 'Automation',
            metricKey: 'reliability',
            metricLabel: 'Reliability',
            metricIcon: '🛡️',
            metricColor: '#10b981',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            category: 'Automation',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#f59e0b',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        // Communication - 4 metrics
        {
            category: 'Communication',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            category: 'Communication',
            metricKey: 'features',
            metricLabel: 'Features',
            metricIcon: '💬',
            metricColor: '#ec4899',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            category: 'Communication',
            metricKey: 'reliability',
            metricLabel: 'Reliability',
            metricIcon: '🛡️',
            metricColor: '#10b981',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            category: 'Communication',
            metricKey: 'integrations',
            metricLabel: 'Integrations',
            metricIcon: '🔗',
            metricColor: '#6366f1',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        // Cloud Storage - 4 metrics
        {
            category: 'Cloud Storage',
            metricKey: 'easeOfUse',
            metricLabel: 'Ease of Use',
            metricIcon: '👌',
            metricColor: '#8b5cf6',
            displayOrder: 0,
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            category: 'Cloud Storage',
            metricKey: 'capacity',
            metricLabel: 'Capacity',
            metricIcon: '💾',
            metricColor: '#3b82f6',
            displayOrder: 1,
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            category: 'Cloud Storage',
            metricKey: 'security',
            metricLabel: 'Security',
            metricIcon: '🔒',
            metricColor: '#ef4444',
            displayOrder: 2,
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            category: 'Cloud Storage',
            metricKey: 'valueForMoney',
            metricLabel: 'Value for Money',
            metricIcon: '💰',
            metricColor: '#10b981',
            displayOrder: 3,
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
    ];

    await db.insert(genreCriteria).values(sampleCriteria);
    
    console.log('✅ Genre criteria seeder completed successfully - 80 records created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});