import { db } from '@/db';
import { toolTypes } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleToolTypes = [
        {
            subCategoryId: 1,
            name: 'AI Writing Assistants',
            slug: 'ai-writing-assistants',
            description: 'AI-powered content generation and writing assistance',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 1,
            name: 'Grammar & Proofreading',
            slug: 'grammar-proofreading',
            description: 'Automated grammar checking and writing improvement',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 1,
            name: 'Translation Tools',
            slug: 'translation-tools',
            description: 'AI-powered language translation and localization',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 2,
            name: 'Image Generation',
            slug: 'image-generation',
            description: 'AI tools for creating images from text descriptions',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 2,
            name: 'Photo Editing',
            slug: 'photo-editing',
            description: 'AI-powered photo enhancement and manipulation',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 2,
            name: 'Image Analysis',
            slug: 'image-analysis',
            description: 'Computer vision and image recognition tools',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 3,
            name: 'Text-to-Speech',
            slug: 'text-to-speech',
            description: 'Convert text to natural-sounding speech',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 3,
            name: 'Voice Cloning',
            slug: 'voice-cloning',
            description: 'AI-powered voice synthesis and cloning',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 3,
            name: 'Music Generation',
            slug: 'music-generation',
            description: 'AI tools for creating music and audio',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 4,
            name: 'Project Planning',
            slug: 'project-planning',
            description: 'Tools for planning and managing projects',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 4,
            name: 'To-Do Lists',
            slug: 'todo-lists',
            description: 'Simple task lists and reminders',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 4,
            name: 'Team Collaboration',
            slug: 'team-collaboration',
            description: 'Collaborative task and project management',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 5,
            name: 'Time Tracking',
            slug: 'time-tracking',
            description: 'Track and analyze time spent on tasks',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 5,
            name: 'Pomodoro Timers',
            slug: 'pomodoro-timers',
            description: 'Focus timers using the Pomodoro Technique',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 5,
            name: 'Calendar Apps',
            slug: 'calendar-apps',
            description: 'Schedule management and calendar tools',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 6,
            name: 'Note-Taking',
            slug: 'note-taking',
            description: 'Digital note-taking and organization',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 6,
            name: 'Knowledge Bases',
            slug: 'knowledge-bases',
            description: 'Centralized information and documentation systems',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 6,
            name: 'Research Tools',
            slug: 'research-tools',
            description: 'Tools for academic and professional research',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 7,
            name: 'Logo Design',
            slug: 'logo-design',
            description: 'Logo creation and branding tools',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 7,
            name: 'Print Design',
            slug: 'print-design',
            description: 'Tools for print media and physical design',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 7,
            name: 'Digital Graphics',
            slug: 'digital-graphics',
            description: 'Web and social media graphics creation',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 8,
            name: 'Wireframing',
            slug: 'wireframing',
            description: 'Create wireframes and mockups',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 8,
            name: 'Prototyping',
            slug: 'prototyping',
            description: 'Interactive prototyping and user testing',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 8,
            name: 'Design Systems',
            slug: 'design-systems',
            description: 'Component libraries and design systems',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 9,
            name: 'Video Editing',
            slug: 'video-editing',
            description: 'Professional video editing software',
            displayOrder: 0,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 9,
            name: 'Motion Graphics',
            slug: 'motion-graphics',
            description: 'Animated graphics and visual effects',
            displayOrder: 1,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            subCategoryId: 9,
            name: 'Animation',
            slug: 'animation',
            description: '2D and 3D animation tools',
            displayOrder: 2,
            isActive: true,
            toolCount: 0,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(toolTypes).values(sampleToolTypes);
    
    console.log('✅ Tool types seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});