import { db } from '@/db';
import { tools } from '@/db/schema';

async function main() {
    const sampleTools = [
        {
            title: 'Timeular',
            description: 'Timeular revolutionizes time tracking with its unique physical tracking cube and intuitive app. Unlike traditional time trackers that rely on manual entries, Timeular uses an 8-sided dice that you flip to start tracking different activities. Each side represents a task or project, making time tracking as simple as flipping the cube. The companion app automatically logs your time and generates insightful reports about how you spend your day. What sets Timeular apart is its focus on work-life balance, offering features like automatic break reminders and productivity analytics that help you understand not just where your time goes, but how to optimize it. Perfect for freelancers, consultants, and anyone who needs to track billable hours or simply wants better awareness of their time allocation. The visual reports make it easy to spot time-wasting patterns and adjust your schedule accordingly. The hardware-software integration creates a tangible connection to your work that makes time tracking feel natural rather than burdensome.',
            url: 'https://timeular.com',
            image: '/images/tools/timeular.jpg',
            category: 'productivity',
            pricing: 'paid',
            type: 'web-app',
            features: ['Physical tracking cube', 'Automatic time logging', 'Productivity analytics', 'Break reminders', 'Visual reports', 'Billable hours tracking'],
            popularity: 125,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-10T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-11-10T10:00:00Z').toISOString(),
        },
        {
            title: 'Reflect',
            description: 'Reflect is a minimalist note-taking app that combines the simplicity of Apple Notes with the power of networked thinking. Built specifically for people who want their notes to be fast, private, and interconnected, Reflect uses end-to-end encryption to ensure your thoughts remain secure. The app excels at creating connections between ideas through automatic backlinks and a graph view that visualizes how your notes relate to each other. What makes Reflect a hidden gem is its AI-powered features that help you resurface relevant notes at the right time, making it feel like you have a personal research assistant. The daily note feature encourages journaling and reflection, while calendar integration helps you capture meeting notes effortlessly. Unlike heavyweight tools like Notion or Roam Research, Reflect focuses on speed and simplicity without sacrificing power. The native apps for Mac, Windows, and iOS ensure your notes are always accessible and sync instantly across devices. Perfect for writers, researchers, and knowledge workers who want to build a second brain without the complexity.',
            url: 'https://reflect.app',
            image: '/images/tools/reflect.jpg',
            category: 'productivity',
            pricing: 'paid',
            type: 'web-app',
            features: ['End-to-end encryption', 'Automatic backlinks', 'Graph view', 'AI-powered suggestions', 'Calendar integration', 'Daily notes'],
            popularity: 165,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-15T14:30:00Z').toISOString(),
        },
        {
            title: 'Sunsama',
            description: 'Sunsama transforms task management into a daily ritual that helps you work with intention and achieve work-life balance. Unlike traditional todo apps that encourage endless list-making, Sunsama focuses on realistic daily planning. Every day starts with a guided planning session where you review yesterday, pull in tasks from integrated tools like Asana, Trello, and Gmail, and commit to a realistic workload for today. The timeboxing feature helps you allocate specific times for each task, creating a sustainable schedule that respects your energy levels. What makes Sunsama special is its emphasis on reflection and closure. At the end of each day, you review what you accomplished and move incomplete tasks forward with intention. The app tracks your actual vs. planned time, helping you become better at estimating and protecting your time. Integration with calendar apps means your schedule and tasks live in harmony. The evening shutdown ritual helps you mentally disconnect from work, making it easier to maintain boundaries. Perfect for busy professionals, remote workers, and anyone who wants to be more intentional about how they spend their days.',
            url: 'https://sunsama.com',
            image: '/images/tools/sunsama.jpg',
            category: 'productivity',
            pricing: 'paid',
            type: 'web-app',
            features: ['Daily planning ritual', 'Timeboxing', 'Calendar integration', 'Task imports from multiple tools', 'Daily reflection', 'Work-life balance tracking'],
            popularity: 142,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-20T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-20T09:15:00Z').toISOString(),
        },
        {
            title: 'RunJS',
            description: 'RunJS is a desktop JavaScript playground that provides instant feedback as you type, making it perfect for testing code snippets, learning JavaScript, or prototyping ideas. Unlike browser consoles or online REPLs, RunJS runs natively on your machine with full access to Node.js APIs and npm packages. The split-pane interface shows your code on one side and results on the other, updating in real-time as you type. What sets RunJS apart is its focus on developer experience: automatic formatting, intelligent autocomplete, and beautiful error messages make coding feel effortless. The app supports modern JavaScript features including async/await, ES modules, and TypeScript. You can install and import npm packages directly, test API calls, manipulate data, or experiment with new libraries without setting up a project. The notebook feature lets you organize related snippets, and the export functionality makes it easy to save your experiments. RunJS also includes features for accessing clipboard data, working with files, and making HTTP requests. Perfect for developers who want a fast, local environment for JavaScript experimentation without the overhead of creating new projects.',
            url: 'https://runjs.app',
            image: '/images/tools/runjs.jpg',
            category: 'development',
            pricing: 'paid',
            type: 'web-app',
            features: ['Real-time code execution', 'Node.js API access', 'NPM package support', 'TypeScript support', 'Split-pane interface', 'Code notebooks'],
            popularity: 178,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-22T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-22T16:45:00Z').toISOString(),
        },
        {
            title: 'Insomnia',
            description: 'Insomnia is a powerful API client and design tool that makes testing REST, GraphQL, and gRPC APIs delightful. While Postman dominates the market, Insomnia offers a cleaner, more focused experience that developers love. The interface is uncluttered and fast, with intelligent autocomplete that understands your API structure. Environment variables and chaining make it easy to test complex workflows across different environments. What makes Insomnia special is its design-first approach with built-in OpenAPI specification support, allowing you to design APIs before building them. The GraphQL support is exceptional, with automatic schema fetching, query autocomplete, and beautiful documentation generation. Code generation in multiple languages means you can quickly translate your API calls into production code. The collaboration features allow teams to share workspaces and sync across devices. Unlike bulkier alternatives, Insomnia stays lightweight and responsive even with large collections. The plugin system extends functionality, and the active open-source community continuously improves the tool. Perfect for API developers, QA engineers, and anyone who works extensively with web services and wants a modern, efficient testing experience.',
            url: 'https://insomnia.rest',
            image: '/images/tools/insomnia.jpg',
            category: 'development',
            pricing: 'freemium',
            type: 'web-app',
            features: ['REST and GraphQL support', 'Environment variables', 'OpenAPI specification', 'Code generation', 'Team collaboration', 'Plugin system'],
            popularity: 189,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-25T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-25T11:20:00Z').toISOString(),
        },
        {
            title: 'Polypane',
            description: 'Polypane is a browser built specifically for developers and designers who need to test responsive websites efficiently. Instead of manually resizing your browser window or using device emulators, Polypane shows multiple viewport sizes simultaneously in synchronized panes. Any interaction in one pane is mirrored across all panes, letting you see how your site responds across different screen sizes in real-time. What makes Polypane a hidden gem is its deep integration of web development tools: built-in accessibility testing, performance monitoring, SEO checks, and social media preview generators. The debug tools highlight responsive design issues, show you exactly where elements overflow or break, and provide actionable suggestions for fixes. The app includes device presets for popular phones, tablets, and desktops, plus custom viewport creation. Screenshot and video recording features capture all panes simultaneously, making it easy to demonstrate responsive behavior to clients or teammates. The live reloading works flawlessly, and the workspace management lets you save and switch between different testing configurations. Perfect for front-end developers, designers, and QA teams who want to catch responsive design issues before they reach production.',
            url: 'https://polypane.app',
            image: '/images/tools/polypane.jpg',
            category: 'development',
            pricing: 'paid',
            type: 'web-app',
            features: ['Multi-viewport testing', 'Synchronized interactions', 'Built-in accessibility testing', 'Performance monitoring', 'Device presets', 'Screenshot all viewports'],
            popularity: 156,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-11-28T13:50:00Z').toISOString(),
            updatedAt: new Date('2024-11-28T13:50:00Z').toISOString(),
        },
        {
            title: 'Coolors',
            description: 'Coolors is an incredibly fast color scheme generator that helps designers create beautiful color palettes in seconds. Unlike traditional color tools that require manual adjustment of each color, Coolors uses an intelligent algorithm to generate harmonious five-color palettes with a single spacebar press. The magic happens in the refinement: lock colors you like and generate new variations for the rest, drag to reorder, adjust hue and saturation with intuitive sliders, or upload an image to extract its color palette. What makes Coolors special is its focus on speed and exploration. The keyboard shortcuts make palette generation feel like playing an instrument, and the ability to save palettes to collections helps you build a personal color library. The app includes accessibility tools to check color contrast ratios, ensuring your designs meet WCAG standards. Export options include CSS, SCSS, SVG, PNG, PDF, and even integration with popular design tools like Adobe and Figma. The gradient generator creates smooth transitions between colors, and the color picker works with HEX, RGB, HSL, and LAB formats. Perfect for designers, developers, and anyone who needs inspiring color combinations quickly.',
            url: 'https://coolors.co',
            image: '/images/tools/coolors.jpg',
            category: 'design',
            pricing: 'freemium',
            type: 'web-app',
            features: ['Instant palette generation', 'Image color extraction', 'Accessibility checker', 'Multiple export formats', 'Gradient generator', 'Keyboard shortcuts'],
            popularity: 194,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-01T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-01T10:30:00Z').toISOString(),
        },
        {
            title: 'Nucleo',
            description: 'Nucleo is a comprehensive icon library and management tool that gives designers and developers access to over 40,000 icons in a native desktop application. Unlike web-based icon libraries that require constant searching and downloading, Nucleo provides instant local access with powerful search and filtering capabilities. The real power lies in the customization features: adjust stroke width, change colors, and modify icons directly in the app before exporting. What makes Nucleo a hidden gem is its organization system. Create custom collections, tag icons for easy retrieval, and build project-specific icon sets that you can share with your team. The app supports multiple export formats including SVG, PNG, icon fonts, and even React components, making it versatile for any workflow. The drag-and-drop functionality works seamlessly with design tools like Sketch, Figma, and Adobe XD. Regular updates add new icons based on design trends and user requests. The licensing is simple and generous, allowing commercial use without attribution. The offline-first approach means you are never dependent on internet connectivity to access your icons. Perfect for designers and developers who want a professional icon solution without subscription fatigue.',
            url: 'https://nucleoapp.com',
            image: '/images/tools/nucleo.jpg',
            category: 'design',
            pricing: 'paid',
            type: 'web-app',
            features: ['40,000+ icons library', 'Icon customization', 'Multiple export formats', 'Custom collections', 'Design tool integration', 'Offline access'],
            popularity: 138,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-03T15:10:00Z').toISOString(),
            updatedAt: new Date('2024-12-03T15:10:00Z').toISOString(),
        },
        {
            title: 'Plausible',
            description: 'Plausible is a lightweight, privacy-first analytics platform that provides all the insights you need without the bloat and privacy concerns of Google Analytics. The entire dashboard fits on a single page, giving you immediate visibility into visitor numbers, traffic sources, top pages, and conversion goals without endless clicking through menus. What makes Plausible special is its commitment to user privacy: no cookies, no cross-site tracking, and full GDPR compliance out of the box. The script is incredibly lightweight at under 1KB, which means it does not slow down your site like traditional analytics tools. Despite its simplicity, Plausible provides powerful features including custom event tracking, goal conversions, UTM campaign tracking, and detailed referrer information. The real-time dashboard shows you what is happening on your site right now, and the email reports keep you informed without requiring daily logins. The open-source nature means complete transparency about how your data is handled, and the option to self-host gives you complete control. The interface is so intuitive that anyone on your team can understand the metrics without training. Perfect for indie developers, small businesses, and anyone who values user privacy while still needing actionable website analytics.',
            url: 'https://plausible.io',
            image: '/images/tools/plausible.jpg',
            category: 'marketing',
            pricing: 'paid',
            type: 'web-app',
            features: ['Privacy-first analytics', 'Single-page dashboard', 'Lightweight script', 'GDPR compliant', 'Real-time data', 'Open-source'],
            popularity: 172,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-05T09:40:00Z').toISOString(),
            updatedAt: new Date('2024-12-05T09:40:00Z').toISOString(),
        },
        {
            title: 'Buttondown',
            description: 'Buttondown is a delightfully simple newsletter platform built for writers who want to focus on content rather than marketing automation. Unlike bloated email marketing tools with dozens of features you will never use, Buttondown provides exactly what you need to send beautiful newsletters: a clean writing interface, subscriber management, and reliable delivery. What makes Buttondown a hidden gem is its emphasis on writing quality. The Markdown-based editor feels natural for technical writers and bloggers, with syntax highlighting for code snippets and automatic formatting. The built-in archive creates a beautiful, searchable website of your newsletters automatically, giving your content a permanent home beyond inboxes. Privacy is core to the platform: no tracking pixels, no surveillance, and subscribers can easily export their data. The API and webhooks make it easy to integrate with your existing tools, and the programmatic newsletter creation is perfect for automated digests or notifications. Pricing is straightforward and based solely on subscriber count, not features. The platform handles SPF and DKIM authentication automatically, ensuring high deliverability rates. The migration tools make it painless to switch from other platforms. Perfect for individual writers, developers, and small businesses who want a no-nonsense newsletter solution.',
            url: 'https://buttondown.email',
            image: '/images/tools/buttondown.jpg',
            category: 'marketing',
            pricing: 'freemium',
            type: 'web-app',
            features: ['Markdown-based editor', 'Automatic newsletter archive', 'Privacy-focused', 'API and webhooks', 'Code snippet support', 'Simple pricing'],
            popularity: 148,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-07T14:25:00Z').toISOString(),
            updatedAt: new Date('2024-12-07T14:25:00Z').toISOString(),
        },
        {
            title: 'Hemingway Editor',
            description: 'Hemingway Editor is a unique writing tool that makes your prose bold and clear by highlighting complex sentences, passive voice, and unnecessary adverbs. Named after Ernest Hemingway, who was known for his concise, powerful writing style, the app uses color-coded highlighting to show different types of issues in your text. Yellow sentences are hard to read, red ones are very hard to read, purple highlights show words with simpler alternatives, and blue marks adverbs that could be removed. What makes Hemingway special is its focus on readability rather than grammar. The app calculates a readability grade level, encouraging you to write for a broad audience. Unlike grammar checkers that flag technical errors, Hemingway helps you develop a clearer, more direct writing style. The desktop app works offline, ensuring you can edit without distractions or internet dependency. The formatting options let you export to various formats including Markdown, HTML, and Word. The minimalist interface keeps you focused on writing, with the analysis panel hiding until you need it. The app does not rewrite your content or suggest AI-generated alternatives; it simply helps you recognize and fix clarity issues yourself. Perfect for writers, bloggers, students, and anyone who wants to improve their writing clarity and impact.',
            url: 'https://hemingwayapp.com',
            image: '/images/tools/hemingway.jpg',
            category: 'ai',
            pricing: 'freemium',
            type: 'web-app',
            features: ['Readability scoring', 'Complex sentence detection', 'Passive voice highlighting', 'Adverb detection', 'Offline desktop app', 'Multiple export formats'],
            popularity: 183,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-10T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T11:15:00Z').toISOString(),
        },
        {
            title: 'ContentCal',
            description: 'ContentCal is a visual content planning platform that helps marketers and social media managers organize their content strategy in a beautiful, intuitive calendar interface. Unlike complex social media management tools that overwhelm with features, ContentCal focuses on planning and collaboration. The drag-and-drop calendar makes it easy to visualize your content across channels, spot gaps in your publishing schedule, and ensure consistent posting. What makes ContentCal special is its emphasis on team collaboration and approval workflows. Assign content to team members, set up multi-stage approval processes, and keep everyone aligned on what is being published and when. The content hub stores your best-performing posts and evergreen content for easy repurposing. Smart scheduling suggests optimal posting times based on your audience engagement patterns. The platform integrates with major social networks including Instagram, Facebook, Twitter, LinkedIn, and Pinterest, allowing you to schedule and publish from one place. The analytics dashboard shows performance across channels, helping you understand what content resonates. The mobile app ensures you can manage your content calendar on the go. Perfect for marketing teams, agencies, and solo entrepreneurs who want to plan content strategically rather than posting reactively.',
            url: 'https://contentcal.io',
            image: '/images/tools/contentcal.jpg',
            category: 'ai',
            pricing: 'freemium',
            type: 'web-app',
            features: ['Visual content calendar', 'Drag-and-drop planning', 'Approval workflows', 'Content hub', 'Smart scheduling', 'Multi-channel publishing'],
            popularity: 161,
            isFeatured: true,
            status: 'approved',
            submittedByUserId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            createdAt: new Date('2024-12-12T16:55:00Z').toISOString(),
            updatedAt: new Date('2024-12-12T16:55:00Z').toISOString(),
        },
    ];

    await db.insert(tools).values(sampleTools);
    
    console.log('✅ Featured hidden gems seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});