import { db } from '@/db';
import { blogComments } from '@/db/schema';

async function main() {
    const sampleComments = [
        // Post 1 (ChatGPT Guide): 5 comments (4 approved, 1 pending)
        {
            postId: 1,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'Excellent guide! The examples really helped me understand the best practices for prompting.',
            status: 'approved',
            createdAt: new Date('2024-01-16T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-16T10:30:00Z').toISOString(),
        },
        {
            postId: 1,
            userId: null,
            authorName: 'Sarah Chen',
            authorEmail: 'sarah.chen@example.com',
            content: 'Has anyone tried using these prompting techniques for technical documentation? Would love to hear experiences.',
            status: 'approved',
            createdAt: new Date('2024-01-16T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-01-16T14:20:00Z').toISOString(),
        },
        {
            postId: 1,
            userId: null,
            authorName: 'Mike Johnson',
            authorEmail: 'mike.j@email.com',
            content: 'Great tutorial! The step-by-step screenshots really helped me get started.',
            status: 'approved',
            createdAt: new Date('2024-01-17T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-17T09:15:00Z').toISOString(),
        },
        {
            postId: 1,
            userId: null,
            authorName: 'Emily Rodriguez',
            authorEmail: 'emily.r@workspace.com',
            content: 'The section about context management was particularly useful. Thanks for sharing!',
            status: 'approved',
            createdAt: new Date('2024-01-18T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-01-18T11:45:00Z').toISOString(),
        },
        {
            postId: 1,
            userId: null,
            authorName: 'David Kim',
            authorEmail: 'david.kim@techmail.com',
            content: 'Could you expand on the advanced prompting strategies in a follow-up article?',
            status: 'pending',
            createdAt: new Date('2024-01-19T16:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-19T16:30:00Z').toISOString(),
        },

        // Post 2 (Top AI Tools): 6 comments (5 approved, 1 spam)
        {
            postId: 2,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'This comparison saved me hours of research. Really appreciate the detailed breakdown of each tool.',
            status: 'approved',
            createdAt: new Date('2024-01-21T08:45:00Z').toISOString(),
            updatedAt: new Date('2024-01-21T08:45:00Z').toISOString(),
        },
        {
            postId: 2,
            userId: null,
            authorName: 'Jessica Martinez',
            authorEmail: 'jessica.m@startup.io',
            content: 'Would love to see pricing comparisons for teams. Are any of these better for collaborative work?',
            status: 'approved',
            createdAt: new Date('2024-01-21T13:20:00Z').toISOString(),
            updatedAt: new Date('2024-01-21T13:20:00Z').toISOString(),
        },
        {
            postId: 2,
            userId: null,
            authorName: 'Tom Williams',
            authorEmail: 'tom.williams@agency.com',
            content: 'Been using Claude for a month now and it's been amazing for coding tasks. Highly recommend!',
            status: 'approved',
            createdAt: new Date('2024-01-22T10:10:00Z').toISOString(),
            updatedAt: new Date('2024-01-22T10:10:00Z').toISOString(),
        },
        {
            postId: 2,
            userId: null,
            authorName: 'Lisa Anderson',
            authorEmail: 'lisa.a@consulting.com',
            content: 'The pros and cons section is really helpful. Makes it easy to decide which tool fits our needs.',
            status: 'approved',
            createdAt: new Date('2024-01-23T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-23T15:30:00Z').toISOString(),
        },
        {
            postId: 2,
            userId: null,
            authorName: 'Robert Taylor',
            authorEmail: 'robert.t@business.net',
            content: 'Thanks for including Gemini! Not many comparisons cover it yet.',
            status: 'approved',
            createdAt: new Date('2024-01-24T09:20:00Z').toISOString(),
            updatedAt: new Date('2024-01-24T09:20:00Z').toISOString(),
        },
        {
            postId: 2,
            userId: null,
            authorName: 'SpamBot2000',
            authorEmail: 'spam@fake-site.xyz',
            content: 'Check out my amazing AI tool that beats all of these! Visit my-sketchy-site.com for FREE trial!!!',
            status: 'spam',
            createdAt: new Date('2024-01-24T18:45:00Z').toISOString(),
            updatedAt: new Date('2024-01-24T18:45:00Z').toISOString(),
        },

        // Post 3 (No-Code AI): 4 comments (3 approved, 1 pending)
        {
            postId: 3,
            userId: null,
            authorName: 'Amanda Foster',
            authorEmail: 'amanda.foster@creative.com',
            content: 'As a designer with no coding background, this article opened up so many possibilities. Thank you!',
            status: 'approved',
            createdAt: new Date('2024-01-26T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-26T11:15:00Z').toISOString(),
        },
        {
            postId: 3,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'The Bubble.io integration examples are spot on. Been using it for client projects with great success.',
            status: 'approved',
            createdAt: new Date('2024-01-27T14:40:00Z').toISOString(),
            updatedAt: new Date('2024-01-27T14:40:00Z').toISOString(),
        },
        {
            postId: 3,
            userId: null,
            authorName: 'James Parker',
            authorEmail: 'james.p@ventures.io',
            content: 'Perfect timing! We're building an MVP and this is exactly what we needed.',
            status: 'approved',
            createdAt: new Date('2024-01-28T10:25:00Z').toISOString(),
            updatedAt: new Date('2024-01-28T10:25:00Z').toISOString(),
        },
        {
            postId: 3,
            userId: null,
            authorName: 'Nina Patel',
            authorEmail: 'nina.patel@digital.com',
            content: 'Are there any limitations with scaling no-code AI apps? Would love to hear more about that.',
            status: 'pending',
            createdAt: new Date('2024-01-29T16:50:00Z').toISOString(),
            updatedAt: new Date('2024-01-29T16:50:00Z').toISOString(),
        },

        // Post 4 (Design Trend): 3 comments (all approved)
        {
            postId: 4,
            userId: null,
            authorName: 'Sophia Lee',
            authorEmail: 'sophia.lee@studio.com',
            content: 'The examples of AI-generated designs are stunning. Already seeing this trend in client requests.',
            status: 'approved',
            createdAt: new Date('2024-02-01T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-01T09:30:00Z').toISOString(),
        },
        {
            postId: 4,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'Great overview of where AI design tools are heading. The accessibility improvements are particularly exciting.',
            status: 'approved',
            createdAt: new Date('2024-02-02T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-02-02T13:15:00Z').toISOString(),
        },
        {
            postId: 4,
            userId: null,
            authorName: 'Marcus Wright',
            authorEmail: 'marcus.w@agency.design',
            content: 'Love how you balanced the opportunities with the challenges. Very realistic perspective.',
            status: 'approved',
            createdAt: new Date('2024-02-03T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-03T11:45:00Z').toISOString(),
        },

        // Post 5 (Midjourney): 5 comments (4 approved, 1 spam)
        {
            postId: 5,
            userId: null,
            authorName: 'Olivia Brown',
            authorEmail: 'olivia.brown@creative.studio',
            content: 'The prompt formulas section is gold! Been experimenting and getting much better results now.',
            status: 'approved',
            createdAt: new Date('2024-02-06T10:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-06T10:20:00Z').toISOString(),
        },
        {
            postId: 5,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'This comprehensive guide covers everything from beginner to advanced. Bookmarking for reference!',
            status: 'approved',
            createdAt: new Date('2024-02-07T14:35:00Z').toISOString(),
            updatedAt: new Date('2024-02-07T14:35:00Z').toISOString(),
        },
        {
            postId: 5,
            userId: null,
            authorName: 'Daniel Garcia',
            authorEmail: 'daniel.g@photography.com',
            content: 'As a photographer, I was skeptical at first, but these techniques are impressive. Great write-up!',
            status: 'approved',
            createdAt: new Date('2024-02-08T09:50:00Z').toISOString(),
            updatedAt: new Date('2024-02-08T09:50:00Z').toISOString(),
        },
        {
            postId: 5,
            userId: null,
            authorName: 'Rachel Cohen',
            authorEmail: 'rachel.cohen@brand.com',
            content: 'The style reference examples are incredibly helpful. Using them for our brand assets now.',
            status: 'approved',
            createdAt: new Date('2024-02-09T15:10:00Z').toISOString(),
            updatedAt: new Date('2024-02-09T15:10:00Z').toISOString(),
        },
        {
            postId: 5,
            userId: null,
            authorName: 'PromoterBot',
            authorEmail: 'bot@spam-domain.com',
            content: 'Why use Midjourney when you can use OUR TOOL? 90% OFF TODAY ONLY! Click here now!!!',
            status: 'spam',
            createdAt: new Date('2024-02-10T20:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-10T20:30:00Z').toISOString(),
        },

        // Post 6 (Remote Stack): 3 comments (2 approved, 1 pending)
        {
            postId: 6,
            userId: null,
            authorName: 'Kevin Zhang',
            authorEmail: 'kevin.zhang@remote.team',
            content: 'Our team uses most of these tools! Would add Loom to the list for async video communication.',
            status: 'approved',
            createdAt: new Date('2024-02-13T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-13T11:30:00Z').toISOString(),
        },
        {
            postId: 6,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'Solid recommendations! The integration tips between tools are especially valuable.',
            status: 'approved',
            createdAt: new Date('2024-02-14T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-14T14:20:00Z').toISOString(),
        },
        {
            postId: 6,
            userId: null,
            authorName: 'Victoria Santos',
            authorEmail: 'victoria.santos@distributed.io',
            content: 'Any recommendations for time zone management tools? That's our biggest challenge right now.',
            status: 'pending',
            createdAt: new Date('2024-02-15T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-15T16:45:00Z').toISOString(),
        },

        // Post 7 (GPT-5 News): 4 comments (all approved)
        {
            postId: 7,
            userId: null,
            authorName: 'Alex Thompson',
            authorEmail: 'alex.thompson@tech.news',
            content: 'The multimodal capabilities sound incredible. Can't wait to see what developers build with it.',
            status: 'approved',
            createdAt: new Date('2024-02-18T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-02-18T09:15:00Z').toISOString(),
        },
        {
            postId: 7,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'Great breakdown of the rumored features. The reasoning improvements could be game-changing.',
            status: 'approved',
            createdAt: new Date('2024-02-19T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-02-19T13:40:00Z').toISOString(),
        },
        {
            postId: 7,
            userId: null,
            authorName: 'Michelle Wong',
            authorEmail: 'michelle.wong@ai.research',
            content: 'Interesting speculation about the release timeline. Based on past patterns, your estimate seems reasonable.',
            status: 'approved',
            createdAt: new Date('2024-02-20T10:55:00Z').toISOString(),
            updatedAt: new Date('2024-02-20T10:55:00Z').toISOString(),
        },
        {
            postId: 7,
            userId: null,
            authorName: 'Christopher Evans',
            authorEmail: 'chris.evans@developer.com',
            content: 'Hope the API pricing remains competitive. That will be key for adoption by smaller teams.',
            status: 'approved',
            createdAt: new Date('2024-02-21T15:25:00Z').toISOString(),
            updatedAt: new Date('2024-02-21T15:25:00Z').toISOString(),
        },

        // Post 8 (Playbook): 2 comments (1 approved, 1 pending)
        {
            postId: 8,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            authorName: null,
            authorEmail: null,
            content: 'This playbook is exactly what our team needed. Clear, actionable, and comprehensive.',
            status: 'approved',
            createdAt: new Date('2024-02-24T11:10:00Z').toISOString(),
            updatedAt: new Date('2024-02-24T11:10:00Z').toISOString(),
        },
        {
            postId: 8,
            userId: null,
            authorName: 'Jennifer Miller',
            authorEmail: 'jennifer.miller@enterprise.com',
            content: 'Would you consider creating a version focused on enterprise implementations? We have specific compliance needs.',
            status: 'pending',
            createdAt: new Date('2024-02-25T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-25T14:30:00Z').toISOString(),
        },
    ];

    await db.insert(blogComments).values(sampleComments);
    
    console.log('✅ Blog comments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});