import { db } from '@/db';
import { communityComments } from '@/db/schema';

async function main() {
    const sampleComments = [
        // Top-level comments (1-20)
        {
            threadId: 1,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Great question! I\'ve been using ChatGPT for content generation and it\'s been a game-changer. The key is in crafting good prompts. Start with clear context, specify your desired output format, and iterate on the results. For blog posts, I typically provide an outline first, then have it expand each section. This approach gives you much more control over the final output and maintains consistency across your content.',
            upvotes: 45,
            downvotes: 2,
            replyCount: 2,
            status: 'active',
            createdAt: new Date('2024-01-16T09:30:00').toISOString(),
            updatedAt: new Date('2024-01-16T09:30:00').toISOString(),
        },
        {
            threadId: 1,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Another tip - use GPT-4 instead of GPT-3.5 for long-form content. The quality difference is significant. Also, consider using tools like Jasper or Copy.ai that are specifically designed for marketing content. They have templates optimized for different content types and often produce better results than raw ChatGPT for specific use cases.',
            upvotes: 32,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-16T10:15:00').toISOString(),
            updatedAt: new Date('2024-01-16T10:15:00').toISOString(),
        },
        {
            threadId: 2,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Midjourney is absolutely worth it if you\'re serious about AI art. The v6 model produces incredibly photorealistic results. However, the learning curve can be steep. Start with simple prompts and gradually add parameters like aspect ratios, style references, and quality settings. The Discord interface takes getting used to, but once you master it, you can create stunning visuals in minutes. I\'ve used it for client presentations and marketing materials with great success.',
            upvotes: 38,
            downvotes: 3,
            replyCount: 1,
            status: 'active',
            createdAt: new Date('2024-01-17T11:20:00').toISOString(),
            updatedAt: new Date('2024-01-17T11:20:00').toISOString(),
        },
        {
            threadId: 2,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'If you\'re just starting out, I\'d actually recommend trying DALL-E 3 through ChatGPT Plus first. It\'s more user-friendly and the integration with ChatGPT makes prompt refinement easier. You can describe what you want in natural language and iterate quickly. Once you understand the basics of AI image generation, then move to Midjourney for more advanced control.',
            upvotes: 28,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-17T14:45:00').toISOString(),
            updatedAt: new Date('2024-01-17T14:45:00').toISOString(),
        },
        {
            threadId: 3,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'I run a small marketing agency and we\'ve integrated several AI tools into our workflow. For content: ChatGPT and Claude for writing, Grammarly for editing. For design: Midjourney and Canva\'s AI features. For social media: Buffer with AI caption generation. The key is not replacing human creativity but augmenting it. We use AI for first drafts and ideation, then our team refines and adds the human touch. This approach has increased our output by 40% while maintaining quality.',
            upvotes: 50,
            downvotes: 2,
            replyCount: 3,
            status: 'active',
            createdAt: new Date('2024-01-18T09:00:00').toISOString(),
            updatedAt: new Date('2024-01-18T09:00:00').toISOString(),
        },
        {
            threadId: 3,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Don\'t forget about automation tools! We use Zapier to connect our AI tools with our project management system. For example, when a client approves a content brief in Notion, it automatically triggers ChatGPT to generate a first draft, which then gets posted to our review board. This level of automation has saved us countless hours of manual work.',
            upvotes: 35,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-18T13:30:00').toISOString(),
            updatedAt: new Date('2024-01-18T13:30:00').toISOString(),
        },
        {
            threadId: 4,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'The free tier limitations really depend on your use case. For ChatGPT, the free version uses GPT-3.5 which is fine for basic tasks but struggles with complex reasoning and longer contexts. You also get lower priority access during peak times. The paid tier ($20/month) gives you GPT-4, faster responses, and access during high-traffic periods. If you use it daily for work, the upgrade pays for itself quickly. For casual use, free tier is perfectly adequate.',
            upvotes: 42,
            downvotes: 1,
            replyCount: 1,
            status: 'active',
            createdAt: new Date('2024-01-19T10:15:00').toISOString(),
            updatedAt: new Date('2024-01-19T10:15:00').toISOString(),
        },
        {
            threadId: 5,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Stable Diffusion is incredibly powerful for local generation. I run it on my RTX 4090 and the speed is impressive - about 2-3 seconds per image at high resolution. The biggest advantage is complete control and privacy. You own your generations, can use any model or LoRA, and there are no content restrictions. However, setup can be technical. I recommend starting with Automatic1111 web UI - it\'s the most user-friendly option and has extensive documentation.',
            upvotes: 47,
            downvotes: 2,
            replyCount: 2,
            status: 'active',
            createdAt: new Date('2024-01-20T08:45:00').toISOString(),
            updatedAt: new Date('2024-01-20T08:45:00').toISOString(),
        },
        {
            threadId: 5,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Hardware requirements: minimum 8GB VRAM for decent performance, 12GB+ recommended. You can run it on less but generation times increase significantly. Also budget for storage - models and LoRAs can take up 100GB+ easily. The community is amazing though, with thousands of custom models on Civitai and HuggingFace. Once you\'re set up, the possibilities are endless.',
            upvotes: 33,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-20T11:20:00').toISOString(),
            updatedAt: new Date('2024-01-20T11:20:00').toISOString(),
        },
        {
            threadId: 6,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Code generation with AI is a massive productivity boost, but it requires the right approach. I use GitHub Copilot for autocomplete and quick snippets, ChatGPT for explaining complex code and architectural decisions, and Claude for refactoring large codebases. The key is understanding that AI is a pair programmer, not a replacement. Always review generated code, test thoroughly, and never blindly trust AI outputs. I\'ve caught subtle bugs that would have been disasters in production.',
            upvotes: 48,
            downvotes: 1,
            replyCount: 2,
            status: 'active',
            createdAt: new Date('2024-01-21T09:30:00').toISOString(),
            updatedAt: new Date('2024-01-21T09:30:00').toISOString(),
        },
        {
            threadId: 6,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'For learning, AI tools are incredible. I use them to explain unfamiliar codebases, generate test cases, and even create documentation. The time savings on boilerplate code alone is worth it. My workflow: write comments describing what I need, let Copilot generate the implementation, then review and refine. This approach has increased my coding speed by at least 30% while actually improving code quality because I spend more time on architecture and less on syntax.',
            upvotes: 36,
            downvotes: 2,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-21T14:00:00').toISOString(),
            updatedAt: new Date('2024-01-21T14:00:00').toISOString(),
        },
        {
            threadId: 7,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Video generation is still in early stages but evolving rapidly. I\'ve tested Runway Gen-2, Pika Labs, and Stable Video Diffusion. For short clips and effects, they\'re impressive. However, for anything longer than 5 seconds or requiring precise control, traditional video editing is still superior. The sweet spot right now is using AI for specific elements: background removal, style transfer, or generating B-roll footage. I wouldn\'t build a complete marketing video with AI yet, but it\'s getting close.',
            upvotes: 40,
            downvotes: 3,
            replyCount: 1,
            status: 'active',
            createdAt: new Date('2024-01-22T10:00:00').toISOString(),
            updatedAt: new Date('2024-01-22T10:00:00').toISOString(),
        },
        {
            threadId: 8,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Voice cloning technology is both amazing and concerning. I use ElevenLabs for creating voiceovers for my educational content. The quality is outstanding - my audience often can\'t tell it\'s AI-generated. The ethical considerations are real though. I always disclose when using AI voices in my content. For business use, make sure you have proper rights and permissions. The technology can clone voices from just a few minutes of audio, which has both creative and security implications.',
            upvotes: 44,
            downvotes: 2,
            replyCount: 1,
            status: 'active',
            createdAt: new Date('2024-01-23T09:15:00').toISOString(),
            updatedAt: new Date('2024-01-23T09:15:00').toISOString(),
        },
        {
            threadId: 9,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'I\'ve built several AI-powered web apps and the landscape changes monthly. Currently using: OpenAI API for LLM capabilities, Vercel AI SDK for streaming responses, Supabase for data storage, and Replicate for image generation. The biggest challenge isn\'t the AI integration itself but managing costs and rate limits. Start small, implement proper caching, and monitor your API usage religiously. A viral feature can quickly rack up thousands in API costs if you\'re not careful.',
            upvotes: 46,
            downvotes: 1,
            replyCount: 2,
            status: 'active',
            createdAt: new Date('2024-01-24T11:30:00').toISOString(),
            updatedAt: new Date('2024-01-24T11:30:00').toISOString(),
        },
        {
            threadId: 9,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'For production apps, consider using LangChain or LlamaIndex for more sophisticated AI workflows. They handle prompt chaining, memory management, and integration with vector databases. This is crucial for building apps that need context awareness and long-term memory. Also look into prompt engineering frameworks - having consistent, well-tested prompts is the difference between a flaky demo and a reliable product.',
            upvotes: 38,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-24T15:45:00').toISOString(),
            updatedAt: new Date('2024-01-24T15:45:00').toISOString(),
        },
        {
            threadId: 10,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Data analysis with AI has transformed how I work. I use ChatGPT Code Interpreter (now called Advanced Data Analysis) almost daily. Upload a CSV, ask for insights, and it generates visualizations and statistical analysis automatically. It\'s particularly good at spotting patterns humans might miss. However, always validate the analysis - AI can make mistakes with edge cases or misinterpret context. I use it as a first pass, then verify critical findings manually or with traditional tools.',
            upvotes: 41,
            downvotes: 2,
            replyCount: 1,
            status: 'active',
            createdAt: new Date('2024-01-25T10:00:00').toISOString(),
            updatedAt: new Date('2024-01-25T10:00:00').toISOString(),
        },
        {
            threadId: 10,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'For more advanced analytics, check out Julius AI or DataRobot. They offer more specialized data science capabilities and can handle larger datasets. The combination of AI-powered exploratory analysis followed by traditional statistical validation is a powerful workflow. I\'ve cut my data analysis time in half while actually improving the depth of insights.',
            upvotes: 34,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-25T13:20:00').toISOString(),
            updatedAt: new Date('2024-01-25T13:20:00').toISOString(),
        },
        {
            threadId: 1,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'One more thing about content generation - don\'t forget about SEO optimization. Tools like SurferSEO and Frase integrate with AI writing to ensure your content ranks well. They analyze top-ranking pages and provide guidance on keywords, structure, and content length. This combination of AI writing and SEO tools is incredibly powerful for content marketing.',
            upvotes: 29,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-26T09:00:00').toISOString(),
            updatedAt: new Date('2024-01-26T09:00:00').toISOString(),
        },
        {
            threadId: 3,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'We also use Notion AI for internal documentation and meeting notes. It\'s not as powerful as ChatGPT but being integrated directly into our workspace is incredibly convenient. The ability to summarize long documents and generate action items from meeting notes has been a huge time-saver for our team.',
            upvotes: 27,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-26T14:30:00').toISOString(),
            updatedAt: new Date('2024-01-26T14:30:00').toISOString(),
        },
        {
            threadId: 7,
            parentCommentId: null,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'For anyone interested in video AI, keep an eye on OpenAI\'s Sora when it releases. The demo videos looked incredibly promising. In the meantime, I\'ve found that combining AI-generated images with traditional video editing software like Premiere Pro or DaVinci Resolve gives the best results. Use AI for assets and effects, human creativity for storytelling and pacing.',
            upvotes: 31,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-27T11:00:00').toISOString(),
            updatedAt: new Date('2024-01-27T11:00:00').toISOString(),
        },

        // Nested replies (21-30)
        {
            threadId: 1,
            parentCommentId: 1,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Absolutely agree on the outline approach! I\'ve found that providing examples of your writing style also helps maintain consistency. Upload a few of your best blog posts and ask ChatGPT to match that tone and style. The results are much more authentic than generic AI content.',
            upvotes: 22,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-16T12:00:00').toISOString(),
            updatedAt: new Date('2024-01-16T12:00:00').toISOString(),
        },
        {
            threadId: 1,
            parentCommentId: 1,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Thanks for the detailed response! Do you have any specific prompt templates you\'d recommend for blog content? I\'m struggling with getting the right balance between informative and engaging.',
            upvotes: 18,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-16T15:30:00').toISOString(),
            updatedAt: new Date('2024-01-16T15:30:00').toISOString(),
        },
        {
            threadId: 2,
            parentCommentId: 3,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Great advice! I\'d add that learning the parameter syntax is crucial. Things like --ar 16:9 for aspect ratio, --stylize for how artistic you want it, and --quality for render quality make a huge difference. The Midjourney documentation has excellent guides on all the parameters.',
            upvotes: 20,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-17T13:45:00').toISOString(),
            updatedAt: new Date('2024-01-17T13:45:00').toISOString(),
        },
        {
            threadId: 3,
            parentCommentId: 5,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'This is exactly the workflow I\'ve been looking for! How do you handle client concerns about AI-generated content? Do you disclose your use of AI tools upfront?',
            upvotes: 15,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-18T11:15:00').toISOString(),
            updatedAt: new Date('2024-01-18T11:15:00').toISOString(),
        },
        {
            threadId: 3,
            parentCommentId: 5,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'We focus on results rather than process. Clients care about quality and timeliness, not whether we used AI tools. That said, we\'re transparent when asked. Most clients are impressed that we\'re using cutting-edge tools to deliver better results faster.',
            upvotes: 25,
            downvotes: 2,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-18T16:00:00').toISOString(),
            updatedAt: new Date('2024-01-18T16:00:00').toISOString(),
        },
        {
            threadId: 4,
            parentCommentId: 7,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'One thing to add - the paid tier also gives you access to DALL-E 3 image generation, which is a nice bonus if you need visual content. And you get priority access to new features like GPTs and the Code Interpreter. For professional use, it\'s definitely worth the investment.',
            upvotes: 19,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-19T13:30:00').toISOString(),
            updatedAt: new Date('2024-01-19T13:30:00').toISOString(),
        },
        {
            threadId: 5,
            parentCommentId: 8,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'For those without high-end GPUs, consider using cloud services like RunPod or Vast.ai. You can rent GPU time for much cheaper than buying hardware, and it\'s great for testing before committing to a local setup.',
            upvotes: 24,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-20T10:30:00').toISOString(),
            updatedAt: new Date('2024-01-20T10:30:00').toISOString(),
        },
        {
            threadId: 5,
            parentCommentId: 8,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Can you recommend any specific LoRAs for product photography? I\'m trying to generate realistic product shots for an e-commerce site.',
            upvotes: 16,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-20T14:15:00').toISOString(),
            updatedAt: new Date('2024-01-20T14:15:00').toISOString(),
        },
        {
            threadId: 6,
            parentCommentId: 10,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'This is solid advice. I\'d emphasize testing even more - AI-generated code often works for happy paths but misses edge cases. Always write comprehensive tests, and consider having AI generate test cases too. The combination catches a lot of potential issues.',
            upvotes: 21,
            downvotes: 0,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-21T12:00:00').toISOString(),
            updatedAt: new Date('2024-01-21T12:00:00').toISOString(),
        },
        {
            threadId: 6,
            parentCommentId: 10,
            userId: 'user_admin_01h4kxt2e8z9y3b1n7m6q5w8r4',
            content: 'Have you tried Cursor AI? It\'s like VS Code but with much better AI integration than Copilot. The ability to reference your entire codebase when generating code is game-changing.',
            upvotes: 17,
            downvotes: 1,
            replyCount: 0,
            status: 'active',
            createdAt: new Date('2024-01-21T16:45:00').toISOString(),
            updatedAt: new Date('2024-01-21T16:45:00').toISOString(),
        },
    ];

    await db.insert(communityComments).values(sampleComments);
    
    console.log('✅ Community comments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});